In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
#Concatenate through different axis
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

Creates a dataframe, as the first series contains an index that the second series doesn't have a value for and vice versa

In [12]:
#Can add keys to label series concatenated
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

X         Y         Z
0  0.122314 -0.309740 -0.488415
1 -0.092266  0.067165  0.605523
2 -1.144843  0.090980 -0.917594
3 -0.925678  0.349076  0.226383

In [15]:
dframe2

Y         Q         X
0 -1.293827  1.276920  1.423009
1  1.506119  0.014623 -0.917950
2 -0.076460  2.339314 -1.117281

In [16]:
#Concatenate with dataframes (similar to series, fills absent values with Nulls)
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0  0.122314 -0.309740 -0.488415       NaN
1 -0.092266  0.067165  0.605523       NaN
2 -1.144843  0.090980 -0.917594       NaN
3 -0.925678  0.349076  0.226383       NaN
0  1.423009 -1.293827       NaN  1.276920
1 -0.917950  1.506119       NaN  0.014623
2 -1.117281 -0.076460       NaN  2.339314

By default keeps the index information from both df

In [17]:
#Ignore the indexes from the df
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0  0.122314 -0.309740 -0.488415       NaN
1 -0.092266  0.067165  0.605523       NaN
2 -1.144843  0.090980 -0.917594       NaN
3 -0.925678  0.349076  0.226383       NaN
4  1.423009 -1.293827       NaN  1.276920
5 -0.917950  1.506119       NaN  0.014623
6 -1.117281 -0.076460       NaN  2.339314

In [18]:
url = 'http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

In [19]:
#Important takeaways: np.concatenate() for numpy, pd.concat() for pandas