In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1, my_list2]

In [8]:
#Creates a matrix (multidimensional array) from the two lists
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
#Find the shape of the Matrix created 
my_array2.shape
#Output shows 2 by 4, every list passed in that list of lists created a new row

(2, 4)

In [11]:
#Find datatype of the array
my_array2.dtype

dtype('int32')

Special Case Arrays

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
my_zeros_array = np.zeros(5)

In [14]:
my_zeros_array.dtype

dtype('float64')

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.02361342e-306,
       3.56174938e-317])

Note: Python 2 makes np.empty the same thing as an array of 0 , Python 3 created a different result

In [17]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

Creates an array in a range of values, from a start position to an end position, in set intervals if parameters are filled