In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
#Randomly reorder a series or rows in a df, and that reordering is known as a Permutation
dframe = DataFrame(np.arange(16).reshape(4,4))

In [3]:
#Create 0,1,2,3 in a random order
blender = np.random.permutation(4)

In [4]:
blender

array([2, 1, 3, 0])

In [5]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
#Based on the results from the blender it randomly shifts the axis
dframe.take(blender)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3

In [7]:
#Permutation with replacement
box = np.array([1,2,3])

In [9]:
#1,2,3 randomly chosen, but this time can be replaced (list can have multiples)
shaker = np.random.randint(0,len(box),size=10)

In [10]:
#Creates an array of different indexes to choose
shaker

array([2, 1, 1, 0, 2, 1, 1, 0, 2, 1])

In [11]:
hand_grabs = box.take(shaker)

In [12]:
#Simulates grabbing marbles 1,2,3 at random from a bag and placing them back in the bag
hand_grabs

array([3, 2, 2, 1, 3, 2, 2, 1, 3, 2])