In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
#Save an array
np.save('myarray',arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#How to load a saved array
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [8]:
arr2 = arr

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Save an array as a zip file
np.savez('ziparray.npz',x=arr1,y=arr2)

In [12]:
#Load multiple arrays
archive_array = np.load('ziparray.npz')

In [13]:
#Calling saved arrays
archive_array['x']

array([0, 1, 2, 3, 4])

In [14]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#Save an array as a text file
np.savetxt('mytextarray.txt',arr,delimiter=',')
#Note for text file, show that the delimiter is a comma, comma separates the values

In [19]:
#Load  a text file
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])