In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Universal Functions (For arrays)- Functions you can call on every value of the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
#Binary Functions (Require two arrays)
A = np.random.randn(10)

A

array([ 1.24518653,  1.28139983, -0.93282961,  0.57961336, -1.08115001,
       -0.22283252, -0.71709251, -0.20608738, -0.24078259,  1.86070528])

In [6]:
B = np.random.randn(10)

B

array([ 0.07200808,  0.13929615, -0.56256194,  0.20513108, -0.31050219,
        0.58280575, -0.1869763 , -1.25390225,  0.72001173, -0.26161511])

In [7]:
np.add(A,B)

array([ 1.31719462,  1.42069597, -1.49539155,  0.78474444, -1.3916522 ,
        0.35997323, -0.90406881, -1.45998963,  0.47922914,  1.59909017])

In [8]:
#Maximum between the two values of the arrays
np.maximum(A,B)

array([ 1.24518653,  1.28139983, -0.56256194,  0.57961336, -0.31050219,
        0.58280575, -0.1869763 , -0.20608738,  0.72001173,  1.86070528])

In [9]:
#For full and extensive list of all Universal Functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True